### PR TITLE
Check sub interfaces in PointsToGraph.canCast

### PR DESCRIPTION
**Pull request by yelite**

### CODE REVIEW

**Comment by yelite** [comment]
And for class to class check, `fromClass.equals(toClass)`, I found the latest soot will randomly create multiple class objects for the same class. Maybe check the class name is better?

**Comment by rohanpadhye** [comment]
Thanks for the contribution! 

I'm wondering why the sub-interface check and super-class check is combined into the same block. Shouldn't these be separate `else if` clauses? Or are you relying on the invariant that `fromClass.getInterfaceCount > 0` implies `fromClass.hasSuperClass() == true` because `java.lang.Object` does not implement any interface?

**Comment by rohanpadhye** [comment]
@yelite : Regarding equality comparison between classes -- If Soot creates multiple objects for the same class, it should override `Object.equals` to ensure that these distinct instances represent the same class. If not, it is probably a bug with Soot, as there should not be two semantically distinct classes with the same name in a given `Scene`. This is guaranteed as `Scene.getSootClass(String name)` returns a single  `SootClass` object for a given fully-qualified name.

**Comment by yelite** [comment]
It can be 
```java
if (fromClass.implementsInterface(toClass.toString())) {
	return true;
} else if (fromClass.hasSuperclass() && canCast(fromClass.getSuperclass(), toClass)) {
        return true;
} else if (fromClass.getInterfaceCount() > 0) {
	for (SootClass subInterface: fromClass.getInterfaces()) {
		if (canCast(subInterface, toClass)) {
			return true;
		}
	}
        return false;
} else {
	return false;
}
```

It's hard to put loop into predicate without creating a new method, then sub interface check must be after the super class check. But I think it's faster to do the sub interface case first. Because the inheritance chain for interface is usually much shorter than classes.

**Comment by rohanpadhye** [comment]
I agree, that the sub interface check ought to be before delegating to the superclass.

How about something like?

```java
if (fromClass.implementsInterface(toClass.toString())) {
	return true;
} 

if (fromClass.getInterfaceCount() > 0) {
	// Check sub interfaces and super class
	for (SootClass subInterface: fromClass.getInterfaces()) {
		if (canCast(subInterface, toClass)) {
			return true;
		}
	}
}

if (fromClass.hasSuperclass()) {
	return canCast(fromClass.getSuperclass(), toClass);
} else {
	return false;
}
```

**Comment by yelite** [comment]
Looks good

**Comment by rohanpadhye** [comment]
Excellent. Thanks for the contribution!

**Pull request merged**
